kind: pipeline
type: docker
name: default


steps:
- name: setup
  image: docker
  commands:
    - docker build . -t kkito/proxyhub:latest
  volumes:
  - name: var_run
    path: /var/run
- name: test
  image: kkito/proxyhub:latest
  pull: never
  commands:
  - go version
  - ls -ltrh
  - CGO_ENABLED=0 go test -v  ./...

- name: build
  # image: golang:alpine
  image: kkito/proxyhub:latest
  pull: never
  volumes:
  - name: dist
    path: /drone/src/dist
  commands:
  - go version
  - CGO_ENABLED=0 go build -o proxy_hub .
  - ls -ltrh
  when:
    branch:
    - master
volumes:
- name: var_run
  host:
    path: /var/run